import { GalapagosEditor } from '../../editor';
import { CodeSnapshot } from './code-snapshot';
/** FixGeneratedCode: Fix the code generated by the LLM. */
export declare function FixGeneratedCode(Editor: GalapagosEditor, Source: string, Parent?: CodeSnapshot, try_again?: boolean): Promise<string>;
//# sourceMappingURL=fix-generated-code.d.ts.map