// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Identifier = 1,
  Directives = 2,
  Commands = 3,
  Extensions = 4,
  Reporters = 5,
  TurtleVars = 6,
  PatchVars = 7,
  LinkVars = 8,
  Constants = 9,
  Unsupported = 10,
  LineComment = 11,
  Program = 12,
  Numeric = 13,
  String = 14
