// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Identifier = 1,
  Directive = 2,
  Command = 3,
  Extension = 4,
  Reporter = 5,
  TurtleVar = 6,
  PatchVar = 7,
  LinkVar = 8,
  Constant = 9,
  Unsupported = 10,
  LineComment = 11,
  Program = 12,
  Numeric = 13,
  String = 14,
  Extensions = 18
